apimServiceName: [prod apim instance name goes here]
namedValues:
  - name: environment
    displayName: environment
    value: "https://www.search.com"
  - name: mysecretvalue
    displayName: mysecretvalue
    keyVault:
      identityClientId: [idnetity client id goes here]
      secretIdentifier: [your url here]
  - name: testSecret
    displayName: testSecret
    value: "{#testSecretValue#}"
loggers:
  - name: apim-lab-insights
    loggerType: applicationInsights
    description: prod application insights
    resourceId: "/subscriptions/[your guid here]/resourceGroups/
                  rg-apim-lab-prod/providers/microsoft.insights/components/apim-lab-prod-insights"
    credentials:
      instrumentationKey: "{{Logger-Credentials--62825ade46346113589affc1}}"
      isBuffered: true
diagnostics:
  - name: applicationinsights
    verbosity: Error
    loggerId: "/subscriptions/[subscription Guid goes here]/resourceGroups/rg-apim-lab-prod/providers/Microsoft.ApiManagement/service/apim-prod-wk-05102022/loggers/apim-lab-prod-insights" 
apis:
  - name: demo-conference-api
    diagnostics:
      - name: applicationinsights
        verbosity: Error
        loggerId: "/subscriptions/[subscription Guid goes here]/resourceGroups/rg-apim-lab-prod/providers/Microsoft.ApiManagement/service/apim-prod-wk-05102022/loggers/apim-lab-prod-insights"
  - name: myapi
    serviceUrl: https://mysite.com
backends:
  - name: helloworldfromfuncapp
    url: "https://helloworldfromprodfuncapp.azurewebsites.net/api"
    resourceid: "https://management.azure.com/subscriptions/[subscription Guid goes here]/resourceGroups/rg-apim-lab-prod/providers/Microsoft.Web/sites/helloworldfromprodfuncapp"
  - name: LogicApp_helloworldfromlogicapp_rg-apim-lab_77fadbdc74f14ce88962b34400a1f170
    url: "https://prod-75.eastus.logic.azure.com/workflows/[guid goes here]/triggers"
    resourceid: "https://management.azure.com/subscriptions/[subscription Guid goes here]/resourceGroups/rg-apim-lab-prod/providers/Microsoft.Logic/workflows/helloworldfromprodlogicapp"
 
 
